name: Run my Python

on:
  schedule:
    - cron: '59 7 18 9 *'
      timezone: 'Asia/Hong_Kong'
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python
        run: python iphone.py
